### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Minteck** [astryzia/stalkerware-urls#8]
Hello,

I am the owner of [unchainedtech.minteck.ro.lt](https://unchainedtech.minteck.ro.lt) (was blogchain.minteck.ro.lt before) and [minteck.ro.lt](https://minteck.ro.lt). Why are my websites on your list? What is your list about?

Thanks.

----

**Edit:** It seems your list is related to spyware. My websites have nothing to do with spyware, could you please remove them from your list? Thanks.

**Edit 2:** Commit 6c8e67b28519c1f2c725bea078d9b6544f46041f, from June 29th, added the two websites to your list.

**Comment by astryzia** [comment]
removed! thanks for letting me know about the false positive
